### ISSUE TITLE
Even more necessary for Qt6

### ISSUE THREAD

**Issue by bulvara** [hdijkema/qtmultimedia-plugin-ffmpeg#1]
Hi Hans,

I'm happily using a GStreamer-free system thanks to this plugin. Qt6 only supports the GStreamer mess: https://github.com/qt/qtmultimedia/blob/6.3.1/src/multimedia/platform/qplatformmediaintegration.cpp#L47

It would be great if you could create a version for Qt6, which otherwise only compiles a [dummy implementation](https://github.com/qt/qtmultimedia/blob/6.3.1/src/multimedia/platform/qplatformmediaintegration.cpp#L72) and then fails at runtime.

**Comment by hdijkema** [comment]
In Qt6.4 the Qt company has added FFMPEG support, see https://doc-snapshots.qt.io/qt6-6.4/qtmultimedia-index.html. It's currently a technology preview, but it makes developing Qt6 support for this plugin not relevant.
